### PR TITLE
Changed element array reference from SELECT element to its OPTION children

### PR DESCRIPTION
**Pull request by Leeds-eBooks**
I don't know why this hasn't been mentioned as an issue, it doesn't work for me as originally written. `el` does have a length, but its array values are undefined. Its `children` are the `<option>` elements.

### CODE REVIEW

**Comment by Leeds-eBooks** [comment]
Yes, thanks!

**Comment by blikblum** [comment]
Hi @Leeds-eBooks i tested multiple select and got it to work with a version prior to this change: http://codepen.io/blikblum/pen/NxEYrr 
Mind you saying what is your use case that was not working?

**Comment by Leeds-eBooks** [comment]
My issue was what I wrote above:

> I don't know why this hasn't been mentioned as an issue, it doesn't work for me as originally written. `el` does have a length, but its array values are undefined. Its children are the `<option>` elements.

I found this bug using iOS Safari.

**Comment by Leeds-eBooks** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/item

I see here that the original approach was ok, however it definitely didn't work for me. Browser support at the above link says `Safari ?` so I think this must have been the problem.

Do you think I should revert this merge?

**Comment by blikblum** [comment]
Yes. It will not work with optgroup. I updated the codepen to use a opt group

**Comment by blikblum** [comment]
I suggest to create an example that fails so we can debug.
I tested here with safari ipad and my code pen is working fine

**Comment by Leeds-eBooks** [comment]
Done on #580

**Comment by Leeds-eBooks** [comment]
Can't make it fail anymore, so I've reversed. Sorry for dropping the ball on this one.

**Comment by blikblum** [comment]
I added some tests: https://github.com/mikeric/rivets/pull/581

**Pull request merged**
