### PR TITLE
Added parsing for component attributes to handle constant strings 

### PR DESCRIPTION
**Pull request by jccazeaux**
For backward compatibility reasons, i left the "static attribute" feature.
See issue #478

### CODE REVIEW

**Comment by blikblum** [comment]
Can you add some tests?

**Comment by Leeds-eBooks** [comment]
Yep tests would be good before I merge this, thanks

**Comment by jccazeaux** [comment]
Yep i'll do that. I made this update some time ago and kept it on my github because i thought Rivets was dead. I'm happy to see it come to life again.
And we need tests on components, i don't see any in the specs.

**Comment by blikblum** [comment]
You can use https://github.com/stalniy/rivets/blob/extended-template/spec/rivets/component_binding.js as a base

You can remove 'allows not to pass "template" method' and skip 'renders returned DOM fragment as component template'

**Comment by jccazeaux** [comment]
Great @blikblum thanks

**Comment by jccazeaux** [comment]
@Leeds-eBooks I just added some tests. It includes tests from @blikblum and a test for primitive attributes.

**Comment by stalniy** [comment]
@Leeds-eBooks, @jccazeaux, @blikblum guys I believe this needs a bit more work.

1. Attributes parsing should be moved to separate method (i.e. `parseAttributes`)
2. I'd like to see attributes parsing being configurable. By default it does as it implemented currently but can be overridden to something what I proposed (i.e. `.bind` suffix). I want to have this as it will help me to migrate to more reach frameworks as Aurelia or Angular in the future

What do you think? If you are agree I will make pull request

**Comment by Leeds-eBooks** [comment]
Happy with point 1 but I don't fully understand what you mean with point 2. How would this be configured by the dev? What does it have to do with Angular and Aurelia?

**Comment by stalniy** [comment]
@Leeds-eBooks Ok, lets say it another way. In "my world" readability plays very important role and I don't like to see something like `attr="'my string here'"` and instead I like solution introduced by Angular2 and Aurelia. For static attributes you do it as usually, so everybody knows that `attr="my string here"` is a an attribute with static value and `attr.bind="myVar"` (or `bind-attr="myVar"`) emphasises that here I want to bind a var as attribute value.

That's why I'd like to see this feature being configurable.

**Regarding implementation**: we need only one method `isAttributeStatic(attribute)`. So that, anybody can override it and use whatever syntax he believes is the best for the project.

Does it make sense?

**Comment by stalniy** [comment]
@Leeds-eBooks,  added bit more context: 

So, the implementation is something like this:
```js
class Rivets.ComponentBinding extends Rivets.Binding
  constructor: (@view, @el, @type) ->
    @component = @view.components[@type]
    @static = {}
    @observers = {}
    @upstreamObservers = {}
    parseAttributes(el.attributes)

  parseAttributes: ->
    bindingRegExp = view.bindingRegExp()

    for attribute in @el.attributes or []
      parseAttribute(attribute) unless bindingRegExp.test attribute.name

  parseAttribute: (attribute) ->
    propertyName = @camelCase attribute.name

    if @isAttributeStatic(attribute)
      @static[propertyName] = attribute.value
    else
      token = Rivets.TypeParser.parse(attribute.value)
      if token.type is 0
       @static[propertyName] = token.value
      else 
       @observers[propertyName] = attribute.value  

  isAttributeStatic: (attribute) ->
    # can be override by configuration
    attribute.name in (@component.static or [])
```

So for my case `isAttributeStatic` looks like:
```js
isAttributeStatic: (attribute) ->
  position = attribute.name.indexOf('.bind')
  position != -1 and position != attribute.name.length - '.bind'.length;
```

**Comment by jccazeaux** [comment]
@stalniy if we change the syntax to pass primitive strings, we should change it for binders too. Having two syntaxes would be disturbing

**Comment by stalniy** [comment]
@jccazeaux you are right that means we need more complex solution. 

We need to create smth like binderProvider object and ability to override it

**Comment by blikblum** [comment]
I'm in favor of removing ```attr="'my string here'"``` syntax at all both at binder and component.
Although instead `attr.bind` i would use `rv-bind-attr="model.prop"` to keep things consistent

**Pull request merged**
