### PR TITLE
Fix/two way formatter publish

### PR DESCRIPTION
**Pull request by Leeds-eBooks**
Makes https://github.com/mikeric/rivets/commit/e64440f4a463ce2850d34f579b55b3eb4061c258 pass.

### CODE REVIEW

**Comment by Leeds-eBooks** [comment]
@jccazeaux & @blikblum I'd appreciate your comments on this PR before I merge. All tests pass, including the one I added for #649.

**Comment by jccazeaux** [comment]
:+1: 
Thanks !

**Comment by Leeds-eBooks** [comment]
Actually I think I've introduced a new bug with this change. Working on this now.

**Comment by Leeds-eBooks** [comment]
Turns out the bug was already there in `0.9.1`. If you have multiple two-way formatters, when you change the value in the view, the formatters are applied twice – once via publish, and then the change in publish triggers the read functions so the formatters aare applied again and the value shown in the model has the formatters applied twice. [Here is a fiddle](https://jsfiddle.net/LeedsEbooks/uy309vyk/1/) demonstrating this bug. Just try replacing the contents of the input with a single character. @jccazeaux This is a bug, right?

**Pull request merged**
