### PR TITLE
Fix #441 error on unobserve

### LINKED ISSUE #441: Cannot read property 'callbacks' of undefined in unobserve
If was updated the values of the scope sereval times (maybe it happens when use "each-*")
Will be received error: `Cannot read property 'callbacks' of undefined`
[JSFilddle](http://jsfiddle.net/y3gDP/29/).
The error is in `unobserve` in  Rivets["public"].adapters['.']:
```js
//...
unobserve: function(obj, keypath, callback) {
      var callbacks, idx, map;
      map = this.weakmap[obj[this.id]];
      callbacks = map.callbacks[keypath];
      if ((idx = callbacks.indexOf(callback)) >= 0) {
        callbacks.splice(idx, 1);
        if (!callbacks.length) {
          delete map.callbacks[keypath];
        }
      }
      this.unobserveMutations(obj[keypath], obj[this.id], keypath);
      return this.cleanupWeakReference(map, obj[this.id]);
    },
//...
```
In come cases variable `map` is `undefined` and this is the cause of the error.
If checking are added error disappears

### PR DESCRIPTION
**Pull request by ZAYEC77**
I add checking of var `map` in `unobserve` method

### CODE REVIEW

**Comment by Leeds-eBooks** [comment]
I'm not sure this fixes the issue, I think it's more deep-rooted. Without fully understanding the issue, this feels like a hack. I tried this out on the js dist file and it just led to other errors.

**Comment by ZAYEC77** [comment]
@Leeds-eBooks, what errors do you got?

**Comment by Leeds-eBooks** [comment]
@ZAYEC77 As I said I didn't use your branch, I just checked for the existence of `map` in the `unobserve` method and I did it in the compiled javascript, not the coffeescript source, so you should take my comment with a pinch of salt, but `map` is referenced in the other methods of the `.` adapter too and so I was getting errors from these other references.

**Comment by mikeric** [comment]
@ZAYEC77, @Leeds-eBooks Thanks for pointing these out. This pull-request partially fixes the problem. Merging this in along with some other changes I've made related to the issue that should hopefully resolve this.

**Pull request merged**
