### PR TITLE
Fix undefined variables

### PR DESCRIPTION
**Pull request by nopnop**
Minor fixes about undefined variable (typo), missing imports and globally scoped variable.

May I suggest the use of [JavaScript Standard Style](https://github.com/feross/standard) for two reasons:
- Easier contributions
- Standard eslinter may track down many little mistakes 

(Anyway, great es6 refactoring ! Thanks)

### CODE REVIEW

**Comment by Leeds-eBooks** [comment]
Thanks for this, I will review this tonight if at all possible and merge in.

**Comment by Leeds-eBooks** [comment]
Hey, sorry for the delay. This is probably _really_ pedantic, but I would probably declare `let lastToken` where it is first assigned [here](https://github.com/mikeric/rivets/pull/522/files#diff-28ef96ceac0325df61d7561fd2b08520R63), rather than at the top of the `parseTemplate` scope? Or did I miss something?

**Comment by nopnop** [comment]
Maybe you right! When I did this, I checked first the current master build first, [here](https://github.com/mikeric/rivets/blob/master/dist/rivets.js#L196) and `lastToken` was scoped outside the `while` block. But there is no need to do this thanks to `let`: I'll amend my PR

**Comment by Leeds-eBooks** [comment]
Ah yes, good old coffeescript transpiling... Thanks! I'll merge once you've committed this.

**Pull request merged**
